get https://naborly-golf-server.herokuapp.com/yardages

###
get http://localhost:3100/yardages

###
post http://localhost:3100/yardages/postYardages
content-type: application/json

{
   "user": "yiqizhang2@gmail.com",
   "clubAdded":{
    "club": "3 Hybrid Degree",     
    "yardage": 88  
   }
}

###
delete http://localhost:3100/yardages/deleteYardages
content-type: application/json

{
   "user": "yiqizhang@gmail.com",
   "club": "9 Iron"         
}