###
post http://localhost:3100/scores/postScores
content-type: application/json

{
   "user": "yiqizhang@gmail.com",
   "scores":{
    "course": "Greyhawk Golf Course - Predator",     
    "date": "Oct 1, 2022",
    "par": 72,
    "player": "Yiqi Zhang",
    "rating": 69.3,
    "score": 90,    
    "slope": 124,
    "tees": "Blue/White",
    "yardage": 6235
   }
}


###
get http://localhost:3100/scores/getScores?user=yiqizhang@gmail.com


###
delete http://localhost:3100/scores/deleteScores
content-type: application/json

{
   "user": "yiqizhang@gmail.com",
   "scores":{
    "course": "Greyhawk Golf Course - Predator",     
    "date": "Oct 1, 2022",
    "par": 72,
    "player": "Yiqi Zhang",
    "rating": 69.3,
    "score": 91,    
    "slope": 124,
    "tees": "Blue/White",
    "yardage": 6235
   }
}


###
get http://localhost:3100/products/getProducts


###
get https://naborly-golf-server.herokuapp.com/yardages

###
get http://localhost:3100/yardages

###
post http://localhost:3100/yardages/postYardages
content-type: application/json

{
   "user": "yiqizhang2@gmail.com",
   "clubAdded":{
    "club": "3 Hybrid Degree",     
    "yardage": 88  
   }
}

###
delete http://localhost:3100/yardages/deleteYardages
content-type: application/json

{
   "user": "yiqizhang@gmail.com",
   "club": "9 Iron"         
}


###
get http://localhost:3100/courses


{
"property": "Royal Woodbine Golf Club",
"latitude": 43.6777088,
"longitude": -79.585545,
"city":"Toronto",
"country":"Canada",
"holes": 18,
"public":true,
"range":false,
"rating":4.0
}


###
get http://localhost:3100/videos/getTutorialVideos